"
" ~/dotfiles/vim/vimrc
"
let &runtimepath.=",~/dotfiles/vim"
let $MYVIMRC="~/dotfiles/vim/vimrc"
let $MODULEPATH="~/dotfiles/vim/modules"

set nocompatible
set noswapfile

set background=dark
colorscheme gruvbox

set nobackup nowritebackup
set belloff=all " turn off annoying bell sound
set incsearch
set ignorecase
set laststatus=2
set clipboard=unnamed
set ruler
set wildmenu " command auotocompletion
set showcmd

set encoding=utf-8
scriptencoding utf-8

syntax on
filetype on

" folding stuff
set foldmethod=syntax
set foldnestmax=10
set foldenable


" sorry f/F and t/T :(
let mapleader=','
let maplocalleader=';'

set backspace=2
set list
set lcs=tab:▸\ ,trail:·,eol:¬,nbsp:_
set wrap
set linebreak

set shiftwidth=4
set shiftround " rounds the indentation to shiftwidth when shifting

set tabstop=4
set smarttab
set expandtab

set backspace=indent,eol,start
set number
set numberwidth=5

set autoindent smartindent
set nojoinspaces " no more pressing spacebar over and over!!

" running python scripts
augroup run_python
    autocmd!
    autocmd FileType python map <buffer> <F9> :w<CR>:exec '!py' shellescape(@%, 1)<CR>
    autocmd FileType python imap <buffer> <F9> <esc>:w<CR>:exec '!py' shellescape(@%, 1)<CR>
augroup END

" style guidelines lmao

augroup style
    autocmd!
    autocmd FileType javascript setlocal textwidth=80
    autocmd FileType vim setlocal formatoptions=cr
augroup END

" to recognize filetype
augroup file_type
    autocmd!
    autocmd BufNewFile,BufRead bash* set syntax=bash
    autocmd BufNewFile,BufRead *gitconfig set syntax=gitconfig
augroup END

" for repeating chars
function! RepeatChar(char, count)
  return repeat(a:char, a:count)
endfunction
nnoremap s :<C-U>exec "normal i".RepeatChar(nr2char(getchar()), v:count1)<CR>
nnoremap S :<C-U>exec "normal a".RepeatChar(nr2char(getchar()), v:count1)<CR>

runtime! modules/*.vim
